spring:

  security:
    user:
      name: user
      password: password
    boot:
      admin:
        client:
          url: http://localhost:8000
          username: admin # 这个username与password用于注册到管理端，使其通过认证
          password: admin
          instance:
            name: ReactiveCrud
            metadata: # 这个name与password用于在注册到管理端时，使管理端有权限获取客户端端点数据
              user.name: ${spring.security.user.name}
              user.password: ${spring.security.user.password}


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.8.3.30:3306/GS_FR?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: gsfruser
    password: GS#fruser323
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    min-idle: 1
    max-active: 20

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
  endpoint:
    health:
      show-details: always

info:
  app:
    name: chapter-mogo